name: Fetch File
on: workflow_dispatch

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download file
        run: curl -L "https://gfve4dog1.mxcontent.net/d/el6jz9k4a6gj9o/43kci9tqmmrbvpp1?ab=0&r=" -o romance-rails-offline_v0.0.5.rar
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add romance-rails-offline_v0.0.5.rar
          git commit -m "Add romance-rails-offline_v0.0.5.rar"
          git push
