name: Fetch and Extract Game
on: workflow_dispatch

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install unrar
        run: sudo apt-get install -y unrar
      - name: Download file
        run: curl -L "https://gfve4dog1.mxcontent.net/d/el6jz9k4a6gj9o/u3nlmfqefq4sqofdbmyi23?ab=0&r=" -o game.rar
      - name: Extract RAR
        run: unrar x game.rar
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Add game files"
          git push
